branch-defaults:
  master:
    environment: mcgqlapi-prod 
global:
  application_name: mcgqlapi
  default_ec2_keyname: XXXXXX
  default_platform: Node.js running on 64bit Amazon Linux/4.12.0
  default_region: us-east-1
  sc: git
