version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Installing Node Modules
          command: npm i
      - run:
         name: Run the tests
         command: npm test
  deploy:
    docker:
      - image: circleci/node:12
    steps: 
      - checkout
      - run:
          name: Installing prod specific dependencies
          command: npm i --production
      - run:
          name: Installing serverless
          command: npm i -g serverless
      - run:
          name: Set AWS creds
          command: export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} && export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - run:
          name: Deploying
          command: serverless deploy --stage prod

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    
