version: 2.1
orbs:
  cli: sbc-orbs/awsebcli@0.0.3
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Installing Node Modules
          command: npm i
      - run:
         name: Run the tests
         command: npm test
  deploy:
    executor: cli/default
    steps: 
      - checkout 
      - cli/install
      - run:
          name: Set environment configuration
          command: eb setenv SAVE_TO_DB=$SAVE_TO_DB MONGODB_URI=$MONGODB_URI DAYS_TIL_SAVE_TO_DB=$DAYS_TIL_SAVE_TO_DB
      - run:
          name: Deploying
          command: eb deploy mcgqlapi-prod

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    
