version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Installing Node Modules
          command: npm i
      - run:
          name: Run the tests
          command: npm test